/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.20
 * Generated at: 2021-06-16 18:06:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import controller.AdminReserveOperationSvl;
import model.*;
import controller.ReserveOperationSvl;

public final class adminReserveUpdate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("model");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("controller.ReserveOperationSvl");
    _jspx_imports_classes.add("controller.AdminReserveOperationSvl");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<!-- メタ -->\r\n");
      out.write("<meta charset=\"UTF-8\"/>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, user-scalable=yes, maximum-scale=1.0, minimum-scale=1.0\"/>\r\n");
      out.write("<meta name=\"description\" content=\"■Restaurante IDEALLE■\"/>\r\n");
      out.write("<meta name=\"keywords\" content=\"\"/>\r\n");
      out.write("<!-- メタ終わり -->\r\n");
      out.write("\r\n");
      out.write("<title>予約変更</title>\r\n");
      out.write("\r\n");
      out.write("<!-- / CSSリンク（アドミン側） -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\" type=\"text/css\" media=\"screen\"/>\r\n");
      out.write("<!-- / CSSリンク（アドミン側） -->\r\n");
      out.write("\r\n");
      out.write("<!-- スクリプト・JS -->\r\n");
      out.write("<!--[if lt IE 9]>\r\n");
      out.write("<script src=\"js/html5.js\"></script>\r\n");
      out.write("<script src=\"js/css3-mediaqueries.js\"></script>\r\n");
      out.write("<![endif]-->\r\n");
      out.write("<script src=\"js/jquery1.4.4.min.js\"></script>\r\n");
      out.write("<script src=\"js/script.js\"></script>\r\n");
      out.write("<!-- スクリプト・JS終わり -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- スタイル -->\r\n");
      out.write("<style>\r\n");
      out.write("<!--\r\n");
      out.write("div#type1{width:100%;display:inline-block;margin:10px auto;max-width: 650px;}\r\n");
      out.write("\r\n");
      out.write("div#type1 li a {\r\n");
      out.write("\t\t\t\tpadding:10px 4px 10px 4px;\r\n");
      out.write("\t\t\t\ttext-decoration: none;\r\n");
      out.write("\t\t\t\tcolor:#FFFFFF;\r\n");
      out.write("\t\t\t\tbackground-color: #660000;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("article.grid{width:31%}\r\n");
      out.write("\r\n");
      out.write("a{color: black;}\r\n");
      out.write("\r\n");
      out.write("div.gridWrapper2{\r\n");
      out.write("width:100%;\r\n");
      out.write("    margin-left: 33.5%;\r\n");
      out.write("\tmargin-right: auto;}\r\n");
      out.write("-->\r\n");
      out.write("</style>\r\n");
      out.write("<!-- スタイル終わり -->\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" media=\"all\" href=\"css/reserve.css\"/>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("<!--\r\n");
      out.write("\r\n");
      out.write("\tfunction check() {\r\n");
      out.write("\t\tif (!$(\"input:radio[name='rsvHhMi']:checked\").val()) {\r\n");
      out.write("\t\t\twindow.alert(\"時間が設定されていません\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}else if($('#cusfrm').find('input[name=\"tel\"]:checked').val() === undefined\r\n");
      out.write("\t\t\t\t&& $('#cusfrm').find('input[name=\"mail\"]:checked').val() === undefined ){\r\n");
      out.write("\t\t\twindow.alert(\"連絡方法を必ず一つ選択してください\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\r\n");
      out.write("\t\t$('#rsv_day,#rsv_person,#rsv_charter').change(\r\n");
      out.write("\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\tvar person = $('#cusfrm').find('select[name=\"person\"] option:selected').val();\r\n");
      out.write("\t\t\t\t\tvar rsvYyMmDd = $('#cusfrm').find('input[name=\"rsvYyMmDd\"]').val();\r\n");
      out.write("\t\t\t\t\tvar courseId = $('#cusfrm').find('select[name=\"courseId\"] option:selected').val();\r\n");
      out.write("\t\t\t\t\tvar charter = $('#cusfrm').find('input[name=\"charter\"]:checked').val();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tif (charter === undefined) {\r\n");
      out.write("\t\t\t\t\t\tcharter = 0;\r\n");
      out.write("\t\t\t\t\t\tif(person > 6){\r\n");
      out.write("\t\t\t\t\t\t\tperson = 2;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t// alert(person + \"/\" + rsvYyMmDd + \"/\" + courseId + \"/\" + charter);\r\n");
      out.write("\t\t\t\t\t$('#frm01').children('input:hidden[name=\"person\"]').val(person);\r\n");
      out.write("\t\t\t\t\t$('#frm01').children('input:hidden[name=\"rsvYyMmDd\"]').val(rsvYyMmDd);\r\n");
      out.write("\t\t\t\t\t$('#frm01').children('input:hidden[name=\"courseId\"]').val(courseId);\r\n");
      out.write("\t\t\t\t\t$('#frm01').children('input:hidden[name=\"charter\"]').val(charter);\r\n");
      out.write("\t\t\t\t\t$('#frm01').submit();\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("//-->\r\n");
      out.write("</script>\r\n");
      out.write("<noscript>\r\n");
      out.write("\t<meta http-equiv=\"refresh\" content=\"0;URL=noscript.jsp\"/>\r\n");
      out.write("</noscript>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- / メニューバー始まり（ホームと同じ） -->\r\n");
      out.write("<div id=\"header\">\r\n");
      out.write("\t<div class=\"inner\">\r\n");
      out.write("\t\t<!-- ロゴ -->\r\n");
      out.write("\t\t<div class=\"logo\">\r\n");
      out.write("\t\t\t<a href=\"home.jsp\">■Restaurante IDEALLE■<br><span>Italian Restaurante</span></a>\r\n");
      out.write("      <h1>welcome to Ideal</h1>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- / ロゴ -->\r\n");
      out.write("\r\n");
      out.write("\t  <!-- メインナビゲーション -->\r\n");
      out.write("    <nav id=\"mainNav\">\r\n");
      out.write("  \t\t<a class=\"menu\" id=\"menu\"><span>Top Menu</span></a>\r\n");
      out.write("\t\t\t<div class=\"panel\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"home.jsp\">トップページ<br><span>Top</span></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"ShowMenuSvl\">メニュー紹介<br><span>Menu</span></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"ReservationStatusSvl\">予約状況<br><span>Reserve</span></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"newsDisplay.jsp\">お知らせ<br><span>News</span></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"UserSvl\">ログイン<br><span>Login</span></a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("      </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("\t\t<!-- メインナビゲーション -->\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- / メニューバー終わり（ホームと同じ） -->\r\n");
      out.write("\r\n");
      out.write("<!-- / アドミンメニューバー始まり-->\r\n");
      out.write("<div align=\"center\">\r\n");
      out.write("<div id=\"type1\">\r\n");
      out.write("<nav id=\"mainNav\">\r\n");
      out.write(" <a class=\"menu\" id=\"menu\"><span>Admin Menu</span></a>\r\n");
      out.write("<div class=\"panel\">\r\n");
      out.write("<ul>\r\n");
      out.write("<li><a href=\"AdminSvl\"><strong>トップ</strong><br><span>Top</span></a></li>\r\n");
      out.write("<li><a href=\"MenuMaintenanceSvl\"><strong>メニューメンテ</strong><br><span>Menu</span></a></li>\r\n");
      out.write("<li><a href=\"NewsSvl\"><strong>お知らせ更新</strong><br><span>News</span></a></li>\r\n");
      out.write("<li><a href=\"AdminReserveListSvl\">予約管理</strong><br><span>Reserve</span></a></li>\r\n");
      out.write("<li><a href=\"HolidaySvl\">定休日変更</strong><br><span>Holiday</span></a></li>\r\n");
      out.write("<li><a href=\"AdminContactSvl\">お問い合わせ一覧</strong><br><span>Contact</span></a></li>\r\n");
      out.write("<li><a href=\"UserListSvl\">ユーザー一覧</strong><br><span>UserList</span></a></li>\r\n");
      out.write("<li><a href=\"AdminLogoffSvl\">ログアウト</strong><br><span>Logout</span></a></li>\r\n");
      out.write("</ul>\r\n");
      out.write("</div>\r\n");
      out.write("</nav>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- / アドミンメニューバー終わり-->\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- コンテンツ -->\r\n");
      out.write("\t");
      model.Admin adminInfo = null;
      synchronized (session) {
        adminInfo = (model.Admin) _jspx_page_context.getAttribute("adminInfo", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (adminInfo == null){
          adminInfo = new model.Admin();
          _jspx_page_context.setAttribute("adminInfo", adminInfo, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write('\r');
      out.write('\n');
      out.write('	');
      model.Reserve reserve = null;
      reserve = (model.Reserve) _jspx_page_context.getAttribute("reserve", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (reserve == null){
        reserve = new model.Reserve();
        _jspx_page_context.setAttribute("reserve", reserve, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      out.write('	');
      java.util.ArrayList courseList = null;
      courseList = (java.util.ArrayList) _jspx_page_context.getAttribute("courseList", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (courseList == null){
        courseList = new java.util.ArrayList();
        _jspx_page_context.setAttribute("courseList", courseList, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      out.write('	');
      java.util.ArrayList reservableList = null;
      reservableList = (java.util.ArrayList) _jspx_page_context.getAttribute("reservableList", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (reservableList == null){
        reservableList = new java.util.ArrayList();
        _jspx_page_context.setAttribute("reservableList", reservableList, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      out.write('	');

		String dateYyMmDd = String.format("%02d", reserve.getRsvYy()) + "-" + String.format("%02d", reserve.getRsvMm()) + "-" + String.format("%02d", reserve.getRsvDd());
		String msg = "";
		if (request.getAttribute("msg") != null) {
			msg = "<div class=\"message\" align=\"center\">" + (String) request.getAttribute("msg") + "</div>";
		}
	
      out.write("\r\n");
      out.write("\t<div id=\"wrapper\">\r\n");
      out.write("\t\t<article class=\"post\">\r\n");
      out.write("\t\t\t<section class=\"content\">\r\n");
      out.write("\t<h1 align=\"center\">予約変更</h1>\r\n");
      out.write("\t");
      out.print(msg);
      out.write("\r\n");
      out.write("\t<div align=\"center\" class=\"reserveInsert\">\r\n");
      out.write("\t\t<form id=\"frm01\" name=\"crform\" method=\"post\" action=\"AdminReserveUpdateSvl\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"person\" value=\"\" />\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"rsvYyMmDd\" value=\"\" />\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"courseId\" value=\"\" />\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"charter\" value=\"\" />\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"rsvId\" value=\"");
      out.print(reserve.getRsvId());
      out.write("\" />\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t\t<label>予約番号</label>\r\n");
      out.write("\t\t\t<div>");
      out.print(reserve.getRsvId());
      out.write("</div>\r\n");
      out.write("\t\t\t<label>予約者名</label>\r\n");
      out.write("\t\t\t<div>");
      out.print(reserve.getUsrName());
      out.write("様</div>\r\n");
      out.write("\t\t<form id=\"cusfrm\" name=\"cusfrm\" method=\"post\" action=\"AdminReserveOperationSvl\" onsubmit=\"return check();\">\r\n");
      out.write("\t\t\t<label>人数</label>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<select id=\"rsv_person\" name=\"person\">\r\n");
      out.write("\t\t\t\t\t");

						String checked = "";
						int max = reserve.getCharter() != 1 ? 6 : 30;
						for (int i = 2; i <= max; i++) {
							checked = i == reserve.getPerson() ? "selected" : "";
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<option value=\"");
      out.print(i);
      out.write('"');
      out.write(' ');
      out.print(checked);
      out.write('>');
      out.print(i);
      out.write("名\r\n");
      out.write("\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t");

						}
					
      out.write("\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t");

						checked = reserve.getCharter() == 1 ? "checked" : "";
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<input id=\"rsv_charter\" type=\"checkbox\" name=\"charter\" value=\"1\" ");
      out.print(checked);
      out.write(" />貸切する\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<label>日にち</label>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<input id=\"rsv_day\" name=\"rsvYyMmDd\" type=\"date\" value=\"");
      out.print(dateYyMmDd);
      out.write("\" min=\"");
      out.print(request.getAttribute("minYyMmDd"));
      out.write("\" max=\"");
      out.print(request.getAttribute("maxYyMmDd"));
      out.write("\"/>\r\n");
      out.write("\t\t\t\t");

					msg = "";
					if (request.getAttribute("holidayMsg") != null) {
						msg = "<p style=\"color:red\" >" + (String) request.getAttribute("holidayMsg") + "</p>";
					}
				
      out.write("\r\n");
      out.write("\t\t\t\t");
      out.print(msg);
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<label>コース(3時間コースのみ)</label>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<select name=\"courseId\">\r\n");
      out.write("\t\t\t\t\t");

						checked = "";
						for (int i = 0; i < courseList.size(); i++) {
							Course cs = (Course) courseList.get(i);
							checked = cs.getCourseId() == reserve.getCourseId() ? "selected" : "";
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<option value=\"");
      out.print(cs.getCourseId());
      out.write('"');
      out.write(' ');
      out.print(checked);
      out.write('>');
      out.print(cs.getCourseName());
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t");

						}
					
      out.write("\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<label>時間(ご予約可能時間帯 17:00～21:00)</label>\r\n");
      out.write("\t\t\t<div class=\"scroll-table\">\r\n");
      out.write("\t\t\t<table class=\"checkTime\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t");

						for (int i = 17 * 60; i < 21 * 60 + 15; i += 15) {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<td><p class=\"dateTime\">");
      out.print(String.format("%02d", i / 60));
      out.write(':');
      out.print(String.format("%02d", i % 60));
      out.write("</p></td>\r\n");
      out.write("\t\t\t\t\t");

						}
					
      out.write("\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t");

						int num = 0;
						int hh = 17;
						int mi = 0;
						String mark;
						String disabled;
						for (int i = 0; i < reservableList.size(); i++) {
							if (mi == 60) {
								mi = 0;
								hh = hh + 1;
							}
							num = (Integer) reservableList.get(i);
							mark = "◎";
							disabled = "";
							if (num == 0) {
								disabled = "disabled";
								mark = "×";
							}
							checked = "";
							if (hh==reserve.getRsvHh() && mi==reserve.getRsvMi() && num != 0){
								checked = "checked";
							}
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" name=\"rsvHhMi\" id=\"rsvHhMi_");
      out.print(i);
      out.write("\" value=\"");
      out.print(hh);
      out.write('：');
      out.print(String.format("%02d", mi));
      out.write('"');
      out.write(' ');
      out.print(disabled);
      out.write(' ');
      out.print(checked);
      out.write("/>\r\n");
      out.write("\t\t\t\t\t\t<label style=\"cursor: hand; cursor: pointer;\" for=\"rsvHhMi_");
      out.print(i);
      out.write('"');
      out.write('>');
      out.print(mark);
      out.write("</label>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t");

						mi = mi + 15;
						}
					
      out.write("\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<label>連絡方法</label>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t");
 checked = reserve.getTel() == 1 ? "checked" : ""; 
      out.write("\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"tel\" value=\"1\" ");
      out.print(checked);
      out.write("/>電話\r\n");
      out.write("\t\t\t\t");
 checked = reserve.getMail() == 1 ? "checked" : ""; 
      out.write("\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"mail\" value=\"1\" ");
      out.print(checked);
      out.write("/>メール\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<label>ご要望</label>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t");
 String exp = reserve.getExp().replace("<br/>", System.lineSeparator()); 
      out.write("\r\n");
      out.write("\t\t\t\t<textarea name=\"exp\" cols=\"80\" rows=\"5\">");
      out.print(exp);
      out.write("</textarea>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"rsvId\" value=\"");
      out.print(reserve.getRsvId());
      out.write("\" />\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"mode\" value=\"");
      out.print(AdminReserveOperationSvl.UPDATE);
      out.write("\" />\r\n");
      out.write("\t\t\t\t<input type=\"submit\" class=\"btn\" value=\"変更\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t<div align=\"center\">\r\n");
      out.write("\t\t\t<a href=\"AdminReserveListSvl\">予約一覧に戻る</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</section>\r\n");
      out.write("\t</article>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
