/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.20
 * Generated at: 2021-06-16 18:07:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import controller.ReserveOperationSvl;
import java.util.*;
import model.*;

public final class adminReserveList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("model");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("controller.ReserveOperationSvl");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<!-- メタ -->\r\n");
      out.write("<meta charset=\"UTF-8\"/>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, user-scalable=yes, maximum-scale=1.0, minimum-scale=1.0\"/>\r\n");
      out.write("<meta name=\"description\" content=\"■Restaurante IDEALLE■\"/>\r\n");
      out.write("<meta name=\"keywords\" content=\"\"/>\r\n");
      out.write("<!-- メタ終わり -->\r\n");
      out.write("<title>管理者予約情報一覧</title>\r\n");
      out.write("\r\n");
      out.write("<!-- / CSSリンク（アドミン側） -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\" type=\"text/css\" media=\"screen\"/>\r\n");
      out.write("<!-- / CSSリンク（アドミン側） -->\r\n");
      out.write("\r\n");
      out.write("<!-- スクリプト・JS -->\r\n");
      out.write("<!--[if lt IE 9]>\r\n");
      out.write("<script src=\"js/html5.js\"></script>\r\n");
      out.write("<script src=\"js/css3-mediaqueries.js\"></script>\r\n");
      out.write("<![endif]-->\r\n");
      out.write("<script src=\"js/jquery1.4.4.min.js\"></script>\r\n");
      out.write("<script src=\"js/script.js\"></script>\r\n");
      out.write("<!-- スクリプト・JS終わり -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- スタイル -->\r\n");
      out.write("<style>\r\n");
      out.write("<!--\r\n");
      out.write("div#type1{width:100%;display:inline-block;margin:10px auto;max-width: 650px;}\r\n");
      out.write("\r\n");
      out.write("div#type1 li a {\r\n");
      out.write("\t\t\t\tpadding:10px 4px 10px 4px;\r\n");
      out.write("\t\t\t\ttext-decoration: none;\r\n");
      out.write("\t\t\t\tcolor:#FFFFFF;\r\n");
      out.write("\t\t\t\tbackground-color: #660000;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("article.grid{width:31%}\r\n");
      out.write("\r\n");
      out.write("a{color: black;}\r\n");
      out.write("\r\n");
      out.write("div.gridWrapper2{\r\n");
      out.write("width:100%;\r\n");
      out.write("    margin-left: 33.5%;\r\n");
      out.write("\tmargin-right: auto;}\r\n");
      out.write("-->\r\n");
      out.write("</style>\r\n");
      out.write("<!-- スタイル終わり -->\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" media=\"all\" href=\"css/reserve.css\"/>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("<!--\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t$('#rsv_day').change(function() {\r\n");
      out.write("\t\t\t$('#cusfrm').submit();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\tfunction deleteRsv(val) {\r\n");
      out.write("\t\tdocument.frm1.rsvId.value = val;\r\n");
      out.write("\t\tdocument.frm1.submit();\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction updateRsv(val) {\r\n");
      out.write("\t\tdocument.frm2.rsvId.value = val;\r\n");
      out.write("\t\tdocument.frm2.submit();\r\n");
      out.write("\t}\r\n");
      out.write("//-->\r\n");
      out.write("</script>\r\n");
      out.write("<noscript>\r\n");
      out.write("\t<meta http-equiv=\"refresh\" content=\"0;URL=noscript.jsp\"/>\r\n");
      out.write("</noscript>\r\n");
      out.write("</head>\r\n");
      model.Admin adminInfo = null;
      synchronized (session) {
        adminInfo = (model.Admin) _jspx_page_context.getAttribute("adminInfo", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (adminInfo == null){
          adminInfo = new model.Admin();
          _jspx_page_context.setAttribute("adminInfo", adminInfo, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write('\r');
      out.write('\n');
      java.util.ArrayList reserveList = null;
      reserveList = (java.util.ArrayList) _jspx_page_context.getAttribute("reserveList", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (reserveList == null){
        throw new java.lang.InstantiationException("bean reserveList not found within scope");
      }
      out.write('\r');
      out.write('\n');
      java.util.HashMap reserveMap = null;
      reserveMap = (java.util.HashMap) _jspx_page_context.getAttribute("reserveMap", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (reserveMap == null){
        throw new java.lang.InstantiationException("bean reserveMap not found within scope");
      }
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<!-- / メニューバー始まり（ホームと同じ） -->\r\n");
      out.write("<div id=\"header\">\r\n");
      out.write("\t<div class=\"inner\">\r\n");
      out.write("\t\t<!-- ロゴ -->\r\n");
      out.write("\t\t<div class=\"logo\">\r\n");
      out.write("\t\t\t<a href=\"home.jsp\">■Restaurante IDEALLE■<br><span>Italian Restaurante</span></a>\r\n");
      out.write("      <h1>welcome to Ideal</h1>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- / ロゴ -->\r\n");
      out.write("\r\n");
      out.write("\t  <!-- メインナビゲーション -->\r\n");
      out.write("    <nav id=\"mainNav\">\r\n");
      out.write("  \t\t<a class=\"menu\" id=\"menu\"><span>Top Menu</span></a>\r\n");
      out.write("\t\t\t<div class=\"panel\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"home.jsp\">トップページ<br><span>Top</span></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"ShowMenuSvl\">メニュー紹介<br><span>Menu</span></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"ReservationStatusSvl\">予約状況<br><span>Reserve</span></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"newsDisplay.jsp\">お知らせ<br><span>News</span></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"UserSvl\">ログイン<br><span>Login</span></a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("      </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("\t\t<!-- メインナビゲーション -->\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- / メニューバー終わり（ホームと同じ） -->\r\n");
      out.write("\r\n");
      out.write("<!-- / アドミンメニューバー始まり-->\r\n");
      out.write("<div align=\"center\">\r\n");
      out.write("<div id=\"type1\">\r\n");
      out.write("<nav id=\"mainNav\">\r\n");
      out.write(" <a class=\"menu\" id=\"menu\"><span>Admin Menu</span></a>\r\n");
      out.write("<div class=\"panel\">\r\n");
      out.write("<ul>\r\n");
      out.write("<li><a href=\"AdminSvl\"><strong>トップ</strong><br><span>Top</span></a></li>\r\n");
      out.write("<li><a href=\"MenuMaintenanceSvl\"><strong>メニューメンテ</strong><br><span>Menu</span></a></li>\r\n");
      out.write("<li><a href=\"NewsSvl\"><strong>お知らせ更新</strong><br><span>News</span></a></li>\r\n");
      out.write("<li><a href=\"AdminReserveListSvl\">予約管理</strong><br><span>Reserve</span></a></li>\r\n");
      out.write("<li><a href=\"HolidaySvl\">定休日変更</strong><br><span>Holiday</span></a></li>\r\n");
      out.write("<li><a href=\"AdminContactSvl\">お問い合わせ一覧</strong><br><span>Contact</span></a></li>\r\n");
      out.write("<li><a href=\"UserListSvl\">ユーザー一覧</strong><br><span>UserList</span></a></li>\r\n");
      out.write("<li><a href=\"AdminLogoffSvl\">ログアウト</strong><br><span>Logout</span></a></li>\r\n");
      out.write("</ul>\r\n");
      out.write("</div>\r\n");
      out.write("</nav>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- / アドミンメニューバー終わり-->\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<a name=\"top\"></a>\r\n");
      out.write("\t<div id=\"wrapper\">\r\n");
      out.write("\t\t<section class=\"content\">\r\n");
      out.write("\t\t\t<article class=\"post\">\r\n");
      out.write("\t\t\t\t<h1 align=\"center\">予約管理</h1>\r\n");
      out.write("\t\t\t\t<div class=\"message\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t");

						if (request.getAttribute("msg") != null) {
							request.getAttribute("msg");
						}
					
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"reservationStatus\">\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<form id=\"cusfrm\" name=\"cusfrm\" method=\"post\" action=\"AdminReserveListSvl\">\r\n");
      out.write("\t\t\t\t\t\t\t<label>確認したい日にちを選択： <input id=\"rsv_day\" name=\"rsvYyMmDd\" type=\"date\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"");
      out.print(request.getAttribute("rsvYyMmDd"));
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\tmax=\"");
      out.print(request.getAttribute("maxYyMmDd"));
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<h3>");
      out.print(request.getAttribute("rsvYyMmDd"));
      out.write("の予約状況</h3>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"scroll-table\">\r\n");
      out.write("\t\t\t\t\t\t<table border=\"1\" cellspacing=\"0\" cellpadding=\"0\" class=\"checkTime\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"reservationTime\">時</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									for (int i = 17; i < 24; i++) {
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"4\" class=\"reservationTime\">");
      out.print(i);
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									}
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"reservationTime\">分</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									for (int i = 17 * 60; i < 24 * 60; i += 15) {
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"reservationTime\">");
      out.print(String.format("%02d", i % 60));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									}
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									String start_end = "";
									String tdTag = "";
									int cnt = 0;
									Reserve rs = new Reserve();

									ArrayList<TableLoc> tbl = Reserve.getTableLoc();
									for (int i = 0; i < tbl.size(); i++) {
										String name = ((TableLoc) tbl.get(i)).getTableName();
										int tableId = ((TableLoc) tbl.get(i)).getTable_id();
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>");
      out.print(name);
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									for (int j = 17 * 60; j < 24 * 60; j += 15) {
											tdTag = "<td></td>";
											int h = j / 60;
											int m = j % 60;
											String key = tableId + "/" + h + ":" + m;
											if (reserveMap.containsKey(key)) {
												String courseName = ((Reserve) reserveMap.get(key)).getCourseName();
												int person = ((Reserve) reserveMap.get(key)).getPerson();
												String charter = ((Reserve) reserveMap.get(key)).getCharter() == 1 ? "【貸切】" : "";
												if(((Reserve) reserveMap.get(key)).getCharter() == 1){
													tdTag = "<td colspan=\"12\" class=\"contents charter\"><a href=\"#rsv_" + ((Reserve) reserveMap.get(key)).getRsvId() + "\"><p>[" + ((Reserve) reserveMap.get(key)).getRsvId() + "]" + courseName + "(" + person + "名)【貸切】</p></a></td>";
												}else{
													tdTag = "<td colspan=\"12\" class=\"contents\"><a href=\"#rsv_" + ((Reserve) reserveMap.get(key)).getRsvId() + "\"><p>[" + ((Reserve) reserveMap.get(key)).getRsvId() + "]" + courseName + "(" + person + "名)</p></a></td>";
												}
												cnt = 1;
											} else if (0 < cnt && cnt < 11) {
												tdTag = "";
												cnt++;
											} else if (cnt == 11) {
												tdTag = "";
												cnt = 0;
											}
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print(tdTag);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									}
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t");

								}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t");

						for (int i = 0; i < reserveList.size(); i++) {
							rs = (Reserve) reserveList.get(i);
							String charter = rs.getCharter() == 1 ? "貸切" : rs.getTableName();
							String tel = rs.getTel() == 1 ? "電話" : "‐";
							String mail = rs.getMail() == 1 ? "メール" : "‐";
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"reserveList\">\r\n");
      out.write("\t\t\t\t\t<p class=\"toTop\" id=\"rsv_");
      out.print(rs.getRsvId());
      out.write("\"><a href=\"#top\">TOPへ戻る</a></p>\r\n");
      out.write("\t\t\t\t\t\t<table border=\"1\" align=\"center\" width=\"60%\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th width=\"30%\">予約番号</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(rs.getRsvId());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>予約者名</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(rs.getUsrName());
      out.write(" 様</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>ご予約日時</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(rs.getRsvYy() + "-" + rs.getRsvMm() + "-" + rs.getRsvDd() + " " + rs.getRsvHh() + ":" + String.format("%02d", rs.getRsvMi()));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>席名</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(charter);
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>最終更新日</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(rs.getAppDate().substring(0, 16));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>コース名</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(rs.getCourseName());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>人数</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(rs.getPerson());
      out.write("名\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>連絡方法</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(tel);
      out.write('／');
      out.print(mail);
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>電話番号</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(rs.getUsrPhone());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>メールアドレス</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(rs.getUsrMail());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>ご要望</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(rs.getExp());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"2\" class=\"subumitTd\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"submit\" value=\"変更\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonclick=\"updateRsv('");
      out.print(rs.getRsvId());
      out.write("')\"></input> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttype=\"submit\" value=\"取消\" onclick=\"deleteRsv('");
      out.print(rs.getRsvId());
      out.write("')\"></input>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t");

						}
					
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<form id=\"frm1\" name=\"frm1\" method=\"post\" action=\"AdminReserveDeleteSvl\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"rsvId\" />\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form id=\"frm2\" name=\"frm2\" method=\"post\" action=\"AdminReserveUpdateSvl\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"rsvId\" />\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</article>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
