/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.20
 * Generated at: 2021-06-16 17:06:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.text.*;
import model.*;
import controller.*;

public final class menuMaintenance_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

 static String fmtNull(String s){
    	if(s==null||s.equals("")){
    		s="&nbsp";
    	}
    	return s;
    }
    
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/incFile.jsp", Long.valueOf(1623852551345L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("java.text");
    _jspx_imports_packages.add("controller");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("model");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<!-- メタ -->\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, user-scalable=yes, maximum-scale=1.0, minimum-scale=1.0\">\r\n");
      out.write("<meta name=\"description\" content=\"■Restaurante IDEALLE■\">\r\n");
      out.write("<meta name=\"keywords\" content=\"\">\r\n");
      out.write("<!-- メタ終わり -->\r\n");
      out.write("\r\n");
      out.write("<title>Menu Maintenance</title>\r\n");
      out.write("<!-- / CSSリンク（アドミン側） -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\" type=\"text/css\" media=\"screen\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/menu.css\" type=\"text/css\" media=\"screen\">\r\n");
      out.write("\r\n");
      out.write("<!-- / CSSリンク（アドミン側） -->\r\n");
      out.write("<!-- スクリプト・JS -->\r\n");
      out.write("<!--[if lt IE 9]>\r\n");
      out.write("<script src=\"js/html5.js\"></script>\r\n");
      out.write("<script src=\"js/css3-mediaqueries.js\"></script>\r\n");
      out.write("<![endif]-->\r\n");
      out.write("<script src=\"js/jquery1.4.4.min.js\"></script>\r\n");
      out.write("<script src=\"js/script.js\"></script>\r\n");
      out.write("<!-- スクリプト・JS終わり -->\r\n");
      out.write("\r\n");
      out.write("<!-- スタイル -->\r\n");
      out.write("<style>\r\n");
      out.write("<!--\r\n");
      out.write("div#type3{width:100%;display:inline-block;margin:10px auto;max-width: 650px;}\r\n");
      out.write("\r\n");
      out.write("div#type3 li a {\r\n");
      out.write("\t\t\t\tpadding:10px 4px 10px 4px;\r\n");
      out.write("\t\t\t\ttext-decoration: none;\r\n");
      out.write("\t\t\t\tcolor:#FFFFFF;\r\n");
      out.write("\t\t\t\tbackground-color: #660000;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("article.grid{width:31%}\r\n");
      out.write("\r\n");
      out.write("a{color: black;}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("div.gridWrapper2{\r\n");
      out.write("width:100%;\r\n");
      out.write("    margin-left: 33.5%;\r\n");
      out.write("\tmargin-right: auto;}\r\n");
      out.write("-->\r\n");
      out.write("</style>\r\n");
      out.write("<!-- スタイル終わり -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- / メニューバー始まり（ホームと同じ） -->\r\n");
      out.write("<div id=\"header\">\r\n");
      out.write("\t<div class=\"inner\">\r\n");
      out.write("\t\t<!-- ロゴ -->\r\n");
      out.write("\t\t<div class=\"logo\">\r\n");
      out.write("\t\t\t<a href=\"home.jsp\">■Restaurante IDEALLE■<br><span>Italian Restaurante</span></a>\r\n");
      out.write("      <h1>welcome to Ideal</h1>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- / ロゴ -->\r\n");
      out.write("\r\n");
      out.write("\t  <!-- メインナビゲーション -->\r\n");
      out.write("    <nav id=\"mainNav\">\r\n");
      out.write("  \t\t<a class=\"menu\" id=\"menu\"><span>Top Menu</span></a>\r\n");
      out.write("\t\t\t<div class=\"panel\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"home.jsp\">トップページ<br><span>Top</span></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"ShowMenuSvl\">メニュー紹介<br><span>Menu</span></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"ReservationStatusSvl\">予約状況<br><span>Reserve</span></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"newsDisplay.jsp\">お知らせ<br><span>News</span></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"UserSvl\">ログイン<br><span>Login</span></a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("      </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("\t\t<!-- メインナビゲーション -->\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- / メニューバー終わり（ホームと同じ） -->\r\n");
      out.write("\r\n");
      out.write("<!-- / アドミンメニューバー始まり-->\r\n");
      out.write("<div align=\"center\">\r\n");
      out.write("<div id=\"type3\">\r\n");
      out.write("<nav id=\"mainNav\">\r\n");
      out.write(" <a class=\"menu\" id=\"menu\"><span>Admin Menu</span></a>\r\n");
      out.write("<div class=\"panel\">\r\n");
      out.write("<ul>\r\n");
      out.write("<li><a href=\"AdminSvl\"><strong>トップ</strong><br><span>Top</span></a></li>\r\n");
      out.write("<li><a href=\"MenuMaintenanceSvl\"><strong>メニューメンテ</strong><br><span>Menu</span></a></li>\r\n");
      out.write("<li><a href=\"NewsSvl\"><strong>お知らせ更新</strong><br><span>News</span></a></li>\r\n");
      out.write("<li><a href=\"AdminReserveListSvl\">予約管理</strong><br><span>Reserve</span></a></li>\r\n");
      out.write("<li><a href=\"HolidaySvl\">定休日変更</strong><br><span>Holiday</span></a></li>\r\n");
      out.write("<li><a href=\"AdminContactSvl\">お問い合わせ一覧</strong><br><span>Contact</span></a></li>\r\n");
      out.write("<li><a href=\"UserListSvl\">ユーザー一覧</strong><br><span>UserList</span></a></li>\r\n");
      out.write("<li><a href=\"AdminLogoffSvl\">ログアウト</strong><br><span>Logout</span></a></li>\r\n");
      out.write("</ul>\r\n");
      out.write("</div>\r\n");
      out.write("</nav>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- / アドミンメニューバー終わり-->\r\n");
      out.write("<div id=\"wrapper\">\r\n");
      out.write("<section class=\"content\">\r\n");
      out.write("<article class=\"post\">\r\n");
      model.Admin adminInfo = null;
      synchronized (session) {
        adminInfo = (model.Admin) _jspx_page_context.getAttribute("adminInfo", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (adminInfo == null){
          adminInfo = new model.Admin();
          _jspx_page_context.setAttribute("adminInfo", adminInfo, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("<h1 id=\"data\">メニューマスターメンテナンス</h1>\r\n");
      out.write("\r\n");

String[]order={"不可","可"};

NumberFormat cf=NumberFormat.getCurrencyInstance(new Locale("ja","JP"));int typeID;
String style="id='type1'";

try{
typeID=Integer.parseInt(request.getParameter("typeID"));
}catch (NumberFormatException e){
	typeID=100;
}

      out.write('\r');
      out.write('\n');
      java.util.ArrayList mType = null;
      mType = (java.util.ArrayList) _jspx_page_context.getAttribute("mType", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (mType == null){
        mType = new java.util.ArrayList();
        _jspx_page_context.setAttribute("mType", mType, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      java.util.ArrayList menu = null;
      menu = (java.util.ArrayList) _jspx_page_context.getAttribute("menu", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (menu == null){
        menu = new java.util.ArrayList();
        _jspx_page_context.setAttribute("menu", menu, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write("\r\n");
      out.write("<div class=\"div1\">\r\n");
      out.write("<table>\r\n");
      out.write("<tr>\r\n");
      out.write("<td id=\"outer1\">\r\n");

for(int i=0 ; i < mType.size() ; i++){
	MenuType mt = (MenuType)mType.get(i);
	if(typeID==mt.getTypeID()){
		style= "id='type2n'";
	}else{
		style= "id='type1n'";
	}


      out.write("\r\n");
      out.write("<div class=\"menumainte\"  >\r\n");
      out.write("<form name=\"frm");
      out.print(i );
      out.write("\" action=\"MenuMaintenanceSvl\" method=\"post\">\r\n");
      out.write("<input type=\"hidden\" name=\"mode\" value=\"0\"/>\r\n");
      out.write("<input type=\"hidden\" name=\"typeID\" value=\"");
      out.print( mt.getTypeID() );
      out.write("\"/>\r\n");
      out.write("<div ");
      out.print( style );
      out.write(" onclick=\"document.frm");
      out.print( i );
      out.write(".submit();\">");
      out.print( mt.getTypeName() );
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
 } 
      out.write("\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td id=\"outer4\">\r\n");
      out.write("<table>\r\n");
      out.write("<caption>&lt;&lt;&lt;\r\n");
 try{ 
      out.write('\r');
      out.write('\n');
      out.print(((Menu)menu.get(0)).getTypeName() );
      out.write('\r');
      out.write('\n');
 }catch(Exception e){ 
      out.write("\r\n");
      out.write("メニューがありません。\r\n");
 } 
      out.write("\r\n");
      out.write("&gt;&gt;&gt;</caption>\r\n");
      out.write("<tr>\r\n");
      out.write("<th id= \"coden\">ID</th>\r\n");
      out.write("<th id= \"menun\">メニュー</th>\r\n");
      out.write("<th id= \"pricen\">価格</th>\r\n");
      out.write("<th id= \"commn\">コメント</th>\r\n");
      out.write("<th id= \"ordn\" >オーダー可</th>\r\n");
      out.write("\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");

	for(int i=0 ; i < menu.size() ; i++){
	Menu m=(Menu)menu.get(i);


      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- <tr>\r\n");
      out.write("<th id= \"coden\">ID</th>\r\n");
      out.write("<th id= \"menun\">メニュー</th>\r\n");
      out.write("<th id= \"pricen\">価格</th>\r\n");
      out.write("<th id= \"commn\">コメント</th>\r\n");
      out.write("<th id= \"ordn\" >オーダー可</th>\r\n");
      out.write("\r\n");
      out.write("</tr> -->\r\n");
      out.write("\r\n");
      out.write("\t<tr id=\"data");
      out.print( i % 2 );
      out.write("\" >\r\n");
      out.write("\t\t<td id=\"coden\" rowspan=\"3\">");
      out.print( m.getMenuId());
      out.write("</td>\r\n");
      out.write("\t\t<td id=\"menu\" rowspan=\"3\">");
      out.print( m.getMenuName());
      out.write("</td>\r\n");
      out.write("\t\t<td id=\"pricen\" rowspan=\"3\">");
      out.print( cf.format(m.getPrice()));
      out.write("</td>\r\n");
      out.write("\t\t<td id=\"comm\"rowspan=\"3\">");
      out.print( fmtNull(m.getDetail()));
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("\t\t<td id=\"ord\"  ><div align=\"center\">");
      out.print( order[m.getOrderFlg()]);
      out.write("</div></td>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td>\t<form action= \"MenuUpdateSvl\" method= \"post\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<input type= \"submit\" value=\"更新\"\r\n");
      out.write(" \t\t\tonclick=\"this.form.mode.value= '");
      out.print( MenuOperationSvl.UPDATE );
      out.write("'\"/>\r\n");
      out.write("\r\n");
      out.write(" \t\t<input type=\"hidden\" name=\"mode\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"menuID\" value=\"");
      out.print( m.getMenuId() );
      out.write("\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"typeID\" value=\"");
      out.print( typeID );
      out.write("\"/>\r\n");
      out.write(" \t\t</form>\r\n");
      out.write(" \t\t</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>\r\n");
      out.write("\t\t<form action= \"MenuDeleteSvl\" method= \"post\" >\r\n");
      out.write("\t\t\t<input type= \"submit\" value=\"削除\"\r\n");
      out.write(" \t\t\tonclick=\"this.form.mode.value= '");
      out.print( MenuOperationSvl.DELETE );
      out.write("'\"/>\r\n");
      out.write("\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"mode\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"menuID\" value=\"");
      out.print( m.getMenuId() );
      out.write("\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"typeID\" value=\"");
      out.print( typeID );
      out.write("\"/>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<tr class=\"td1\">\r\n");
      out.write("\t\t<form action =\"MenuInsertSvl\" method=\"post\">\r\n");
      out.write("\t\t<th colspan=\"7\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<input type=\"hidden\"  name=\"typeID\" value=\"");
      out.print( typeID );
      out.write("\"/>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<input  type=\"hidden\"  name=\"mode\" value=\"");
      out.print( MenuOperationSvl.INSERT );
      out.write("\"/>\r\n");
      out.write("\t\t\t<p id=\"center\"><input id=\"newmenu\" type=\"submit\"  value=\"新しいメニューの追加\"/></p>\r\n");
      out.write("\r\n");
      out.write("\t\t</th>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\r\n");
      out.write("</table><!-- インナーテーブルの終了 -->\r\n");
      out.write("</td>\r\n");
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td id=\"outer2\">\r\n");

for(int i=0 ; i < mType.size() ; i++){
	MenuType mt = (MenuType)mType.get(i);
	if(typeID==mt.getTypeID()){
		style= "id='type2'";
	}else{
		style= "id='type1'";
	}


      out.write("\r\n");
      out.write("<div class=\"menumainte\"  >\r\n");
      out.write("\r\n");
      out.write("<input type=\"hidden\" name=\"mode\" value=\"0\"/>\r\n");
      out.write("<input type=\"hidden\" name=\"typeID\" value=\"");
      out.print( mt.getTypeID() );
      out.write("\"/>\r\n");
      out.write("<div ");
      out.print( style );
      out.write(" onclick=\"document.frm");
      out.print( i );
      out.write(".submit();\">");
      out.print( mt.getTypeName() );
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
 } 
      out.write("\r\n");
      out.write("<td id=\"outer2\">\r\n");
      out.write("<table>\r\n");
      out.write("<caption>&lt;&lt;&lt;\r\n");
 try{ 
      out.write('\r');
      out.write('\n');
      out.print(((Menu)menu.get(0)).getTypeName() );
      out.write('\r');
      out.write('\n');
 }catch(Exception e){ 
      out.write("\r\n");
      out.write("メニューがありません。\r\n");
 } 
      out.write("\r\n");
      out.write("&gt;&gt;&gt;</caption>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<th id= \"code\">ID</th>\r\n");
      out.write("<th id= \"menu\">メニュー</th>\r\n");
      out.write("<th id= \"price\">価格</th>\r\n");
      out.write("<th id= \"comm\">コメント</th>\r\n");
      out.write("<th id= \"ord\">オーダー可</th>\r\n");
      out.write("<th id= \"btn\"colspan=\"2\"></th>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");

	for(int i=0 ; i < menu.size() ; i++){
	Menu m=(Menu)menu.get(i);


      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<tr id=\"data");
      out.print( i % 2 );
      out.write("\" >\r\n");
      out.write("\t\t<td id=\"code\">");
      out.print( m.getMenuId());
      out.write("</td>\r\n");
      out.write("\t\t<td id=\"menu\">");
      out.print( m.getMenuName());
      out.write("</td>\r\n");
      out.write("\t\t<td id=\"price\">");
      out.print( cf.format(m.getPrice()));
      out.write("</td>\r\n");
      out.write("\t\t<td id=\"comm\">");
      out.print( fmtNull(m.getDetail()));
      out.write("</td>\r\n");
      out.write("\t\t<td id=\"ord\"  ><div align=\"center\">");
      out.print( order[m.getOrderFlg()]);
      out.write("</div></td>\r\n");
      out.write("\t\t<form action= \"MenuUpdateSvl\" method= \"post\">\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<input type= \"submit\" value=\"更新\"\r\n");
      out.write(" \t\t\tonclick=\"this.form.mode.value= '");
      out.print( MenuOperationSvl.UPDATE );
      out.write("'\"/>\r\n");
      out.write(" \t\t</td>\r\n");
      out.write(" \t\t<input type=\"hidden\" name=\"mode\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"menuID\" value=\"");
      out.print( m.getMenuId() );
      out.write("\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"typeID\" value=\"");
      out.print( typeID );
      out.write("\"/>\r\n");
      out.write(" \t\t</form>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\r\n");
      out.write("\t\t<form action= \"MenuDeleteSvl\" method= \"post\" >\r\n");
      out.write("\t\t\t<input type= \"submit\" value=\"削除\"\r\n");
      out.write(" \t\t\tonclick=\"this.form.mode.value= '");
      out.print( MenuOperationSvl.DELETE );
      out.write("'\"/>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"mode\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"menuID\" value=\"");
      out.print( m.getMenuId() );
      out.write("\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"typeID\" value=\"");
      out.print( typeID );
      out.write("\"/>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<tr class=\"td1\">\r\n");
      out.write("\t\t<form action =\"MenuInsertSvl\" method=\"post\">\r\n");
      out.write("\t\t<th colspan=\"7\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<input type=\"hidden\"  name=\"typeID\" value=\"");
      out.print( typeID );
      out.write("\"/>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<input  type=\"hidden\"  name=\"mode\" value=\"");
      out.print( MenuOperationSvl.INSERT );
      out.write("\"/>\r\n");
      out.write("\t\t\t<p id=\"center\"><input id=\"newmenu\" type=\"submit\"  value=\"新しいメニューの追加\"/></p>\r\n");
      out.write("\r\n");
      out.write("\t\t</th>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\r\n");
      out.write("</table><!-- インナーテーブルの終了 -->\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</article>\r\n");
      out.write("</section>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
