/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.20
 * Generated at: 2021-06-16 14:18:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import javax.sql.*;
import javax.naming.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

public final class newsDisplay_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.sql");
    _jspx_imports_packages.add("javax.naming");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.time.format.DateTimeFormatter");
    _jspx_imports_classes.add("java.time.LocalDateTime");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, user-scalable=yes, maximum-scale=1.0, minimum-scale=1.0\">\r\n");
      out.write("<meta name=\"description\" content=\"■Restaurante IDEALLE■\">\r\n");
      out.write("<meta name=\"keywords\" content=\"\">\r\n");
      out.write("<title>お知らせ一覧</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\" type=\"text/css\" media=\"screen\">\r\n");
      out.write("<!-- スクリプト・JS -->\r\n");
      out.write("<!--[if lt IE 9]>\r\n");
      out.write("<script src=\"js/html5.js\"></script>\r\n");
      out.write("<script src=\"js/css3-mediaqueries.js\"></script>\r\n");
      out.write("<![endif]-->\r\n");
      out.write("<script src=\"js/jquery1.4.4.min.js\"></script>\r\n");
      out.write("<script src=\"js/script.js\"></script>\r\n");
      out.write("<!-- スクリプト・JS終わり -->\r\n");
      out.write("<style>\r\n");
      out.write("<!--\r\n");
      out.write("th {\r\n");
      out.write("  background: #e9727e;\r\n");
      out.write("  border: solid 1px #ccc;\r\n");
      out.write("  color: #fff;\r\n");
      out.write("  padding: 10px;\r\n");
      out.write("}\r\n");
      out.write("td {\r\n");
      out.write("  border: solid 1px #ccc;\r\n");
      out.write("  padding: 10px;\r\n");
      out.write("}\r\n");
      out.write("@media screen and (max-width: 640px) {\r\n");
      out.write("  .tbl-r03 {\r\n");
      out.write("    width: 90%;\r\n");
      out.write("  }\r\n");
      out.write("  .tbl-r03 tr {\r\n");
      out.write("    display: block;\r\n");
      out.write("    float: left;\r\n");
      out.write("  }\r\n");
      out.write("  .tbl-r03 tr td,\r\n");
      out.write("  .tbl-r03 tr th {\r\n");
      out.write("    border-left: none;\r\n");
      out.write("    display: block;\r\n");
      out.write("    height: 50px;\r\n");
      out.write("  }\r\n");
      out.write("  .tbl-r03 thead {\r\n");
      out.write("    display: block;\r\n");
      out.write("    float: left;\r\n");
      out.write("    width: 30%;\r\n");
      out.write("  }\r\n");
      out.write("  .tbl-r03 thead tr {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("  }\r\n");
      out.write("  .tbl-r03 tbody {\r\n");
      out.write("    display: block;\r\n");
      out.write("    float: left;\r\n");
      out.write("    width: 70%;\r\n");
      out.write("  }\r\n");
      out.write("  .tbl-r03 tbody tr {\r\n");
      out.write("    width: 50%;\r\n");
      out.write("  }\r\n");
      out.write("  .tbl-r03 tr td + td {\r\n");
      out.write("    border-left: none;\r\n");
      out.write("  }\r\n");
      out.write("  .tbl-r03 tbody td:last-child {\r\n");
      out.write("    border-bottom: solid 1px #ccc;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write(".info {padding: 0 1.5em;width: 96%;height: 10em;}\r\n");
      out.write(".info dl {padding: 0.5em 0;}\r\n");
      out.write(".info dt {padding: 0.5em;width: 25em;}\r\n");
      out.write("@media screen and (min-width: 480px) {\r\n");
      out.write(".info {padding: 0 0.5em;width: 98%;height: 15em;}\r\n");
      out.write(".info dt {clear: left;float: left;}\r\n");
      out.write(".info dd {margin-left: 0.5em;border-bottom: 1px solid #ccc;}\r\n");
      out.write("}\r\n");
      out.write(".post{overflow: Auto;}\r\n");
      out.write("-->\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      model.User userInfo = null;
      synchronized (session) {
        userInfo = (model.User) _jspx_page_context.getAttribute("userInfo", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (userInfo == null){
          userInfo = new model.User();
          _jspx_page_context.setAttribute("userInfo", userInfo, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write('\r');
      out.write('\n');

String userName=userInfo.getUsr_name();
System.out.println(userName);
if(userName==null){
      out.write("\r\n");
      out.write("<!-- メニューバー -->\r\n");
      out.write("<div id=\"header\">\r\n");
      out.write("\t<div class=\"inner\">\r\n");
      out.write("\t\t<!-- ロゴ -->\r\n");
      out.write("\t\t<div class=\"logo\">\r\n");
      out.write("\t\t\t<a href=\"home.jsp\">■Restaurante IDEALLE■<br><span>Italian Restaurante</span></a>\r\n");
      out.write("      <h1>welcome to Ideal</h1>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- / ロゴ -->\r\n");
      out.write("\r\n");
      out.write("\t  <!-- メインナビゲーション -->\r\n");
      out.write("    <nav id=\"mainNav\">\r\n");
      out.write("  \t\t<a class=\"menu\" id=\"menu\"><span>Top Menu</span></a>\r\n");
      out.write("\t\t\t<div class=\"panel\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"home.jsp\">トップページ<br><span>Top</span></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"ShowMenuSvl\">メニュー紹介<br><span>Menu</span></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"ReservationStatusSvl\">予約状況<br><span>Reserve</span></a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"active\"><a href=\"newsDisplay.jsp\">お知らせ<br><span>News</span></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"UserSvl\">ログイン<br><span>Login</span></a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("      </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("\t\t<!-- メインナビゲーション -->\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
 }else{
      out.write("\r\n");
      out.write("<div id=\"header\">\r\n");
      out.write("\t<div class=\"inner\">\r\n");
      out.write("\t\t<!-- ロゴ -->\r\n");
      out.write("\t\t<div class=\"logo\">\r\n");
      out.write("\t\t\t<a href=\"home.jsp\">■Restaurante IDEALLE■<br><span>Italian Restaurante</span></a>\r\n");
      out.write("      <h1>welcome to Ideal</h1>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- / ロゴ -->\r\n");
      out.write("\r\n");
      out.write("\t  <!-- メインナビゲーション -->\r\n");
      out.write("    <nav id=\"mainNav\">\r\n");
      out.write("  \t\t<a class=\"menu\" id=\"menu\"><span>Top Menu</span></a>\r\n");
      out.write("\t\t\t<div class=\"panel\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"home.jsp\">トップページ<br><span>Top</span></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"ShowMenuSvl\">メニュー紹介<br><span>Menu</span></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"ReservationStatusSvl\">予約状況<br><span>Reserve</span></a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"active\"><a href=\"newsDisplay.jsp\">お知らせ<br><span>News</span></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"UserSvl\">");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((model.User)_jspx_page_context.findAttribute("userInfo")).getUsr_name())));
      out.write("様マイページ<br><span>MyPage</span></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"UserLogoffSvl\">ログアウト<br><span>Logout</span></a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("      </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("\t\t<!-- メインナビゲーション -->\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
} 
      out.write("\r\n");
      out.write("<!-- / メニューバー終わり（ホーム） -->\r\n");
      out.write("<div id=\"wrapper\">\r\n");
      out.write("<section class=\"content\">\r\n");
      out.write("<div class=\"post\">\r\n");
      out.write("<h1 align=\"center\">メニュー紹介</h1>\r\n");
      out.write("<div class=\"post\">\r\n");
      out.write("<div class=\"info\">\r\n");

request.setCharacterEncoding("utf-8");

InitialContext ic=new InitialContext();
DataSource ds=(DataSource)ic.lookup("java:comp/env/mysql");
Connection con=ds.getConnection();

Statement st=con.createStatement();
String sql="SELECT * FROM news ORDER BY n_date DESC";
st=con.createStatement();
ResultSet rs=st.executeQuery(sql);
while(rs.next()){

      out.write("\r\n");
      out.write("<dt>");
      out.print(rs.getString("title"));
      out.write("</dt>\r\n");
      out.write("<dl>");
      out.print(rs.getString("n_date").substring(0, 16));
      out.write("</dl>\r\n");
      out.write("<dd>");
      out.print(rs.getString("n_message"));
      out.write("</dd>\r\n");
      out.write("\r\n");
}
	ic.close();
	con.close();
	rs.close();

      out.write("\r\n");
      out.write("<br />\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</section>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- フッター -->\r\n");
      out.write("<footer id=\"footer\">\r\n");
      out.write("\t<div class=\"inner\">\r\n");
      out.write("\r\n");
      out.write("  \t<!-- 3カラム -->\r\n");
      out.write("    <section class=\"gridWrapper\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<article class=\"grid\">\r\n");
      out.write("\t  \t\t<!-- ロゴ -->\r\n");
      out.write("\t\t\t\t<p class=\"logo\">\r\n");
      out.write("  \t\t\t\t<a href=\"home.jsp\">■Restaurante IDEALLE■<br><span>Italian Restaurante</span></a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("        <!-- / ロゴ -->\r\n");
      out.write("     \t</article>\r\n");
      out.write("\r\n");
      out.write("      <!-- 電話番号+受付時間 -->\r\n");
      out.write("    \t<article class=\"grid\">\r\n");
      out.write("    \t\t<p class=\"tel\"><span>電話:</span> <strong>011-206-1663</strong></p>\r\n");
      out.write("    \t\t<p class=\"open\">営業時間: 17：00～24：00</p>\r\n");
      out.write("    \t\t<p class=\"open\">定休日: 水曜日</p>\r\n");
      out.write("\t\t\t<!-- / 電話番号+受付時間 -->\r\n");
      out.write("      </article>\r\n");
      out.write("\r\n");
      out.write("    \t<article class=\"grid copyright\">\r\n");
      out.write("      \tCopyright(c) 2016 ホームページサンプル株式会社 All Rights Reserved. Design by <a href=\"http://f-tpl.com\" target=\"_blank\" rel=\"nofollow\">http://f-tpl.com</a><br/>\r\n");
      out.write("      \t<a href=\"AdminSvl\">管理者用</a>\r\n");
      out.write("      </article>\r\n");
      out.write("\r\n");
      out.write("    </section>\r\n");
      out.write("\t\t<!-- / 3カラム -->\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</footer>\r\n");
      out.write("<!-- / フッター 終わり-->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
